/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPortalLinksRouteImport } from './routes/_authenticated/portal-links'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedCoursesCourseIdRouteImport } from './routes/_authenticated/courses.$courseId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalLinksRoute =
  AuthenticatedPortalLinksRouteImport.update({
    id: '/portal-links',
    path: '/portal-links',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesCourseIdRoute =
  AuthenticatedCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/portal-links': typeof AuthenticatedPortalLinksRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/portal/$token': typeof PortalTokenRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/portal-links': typeof AuthenticatedPortalLinksRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/portal/$token': typeof PortalTokenRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/portal-links': typeof AuthenticatedPortalLinksRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/portal/$token': typeof PortalTokenRoute
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/portal-links'
    | '/reports'
    | '/scan'
    | '/sessions'
    | '/students'
    | '/portal/$token'
    | '/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/portal-links'
    | '/reports'
    | '/scan'
    | '/sessions'
    | '/students'
    | '/portal/$token'
    | '/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/portal-links'
    | '/_authenticated/reports'
    | '/_authenticated/scan'
    | '/_authenticated/sessions'
    | '/_authenticated/students'
    | '/portal/$token'
    | '/_authenticated/courses/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalTokenRoute: typeof PortalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal-links': {
      id: '/_authenticated/portal-links'
      path: '/portal-links'
      fullPath: '/portal-links'
      preLoaderRoute: typeof AuthenticatedPortalLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedCoursesRoute
    }
  }
}

interface AuthenticatedCoursesRouteChildren {
  AuthenticatedCoursesCourseIdRoute: typeof AuthenticatedCoursesCourseIdRoute
}

const AuthenticatedCoursesRouteChildren: AuthenticatedCoursesRouteChildren = {
  AuthenticatedCoursesCourseIdRoute: AuthenticatedCoursesCourseIdRoute,
}

const AuthenticatedCoursesRouteWithChildren =
  AuthenticatedCoursesRoute._addFileChildren(AuthenticatedCoursesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedPortalLinksRoute: typeof AuthenticatedPortalLinksRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoursesRoute: AuthenticatedCoursesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedPortalLinksRoute: AuthenticatedPortalLinksRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalTokenRoute: PortalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
